### DISCUSSION TITLE
Multiple Users with Mecha CMS

### DISCUSSION THREAD

**Discussion by synwt** [mecha-cms/mecha#173] [Q&A]
On a web, sometimes it takes more than one author.

```yaml
---
title: Markdown Content
description: Using Markdown syntax in page title, description and content.
author: ['@firstauthor', '@secondauthor', '@thirdauthor']
type: Markdown
...
```

How can Mecha execute it with a PHP script in the layout directory properly, Mas Taufik? So that in the end it renders as we expected.

```php
<?php
	$author = $page->author;
	echo "Authors: " . $author[0] . ", " . $author[1] . " and " . $author[2] . ".";
?>
```

That's not enough. Mecha has `user` and `panel` extensions. Then a PHP script for multiple users should at least issue:

- Author's name
- Author link
- Author's avatar
- and so on (relevant)

Everything refers to and is synchronized with the data in the previously inputted from `user` extension. At least like this:

```html
<p>
    Authors: <a href="/user/firstauthor">First Author</a>, <a href="/user/secondauthor">Second Author</a>, and <a href="/user/thirdauhor">Thrid Author</a>
</p>
```

Maybe entering "multiple users" in the GUI form in the extension `panel` is too cumbersome.  But, *matur nuwun*, thanks for the discussion, Mas Taufik.
