### DISCUSSION TITLE
Manual Input YAML in Text Editor is Deleted by Panel when Page Updated

### DISCUSSION THREAD

**Discussion by nurbaitifitriyani** [mecha-cms/mecha#203] [Q&A]
```yaml
---
title: Page Title
description: Page description.
author: Taufik Nurrohman
type: Markdown
state:
  comment: false
...
```

Halo, semua.

Saya mencoba secara manual melalui editor text memasukkan data di `yaml` berupa `type` dengan nilai `Markdown` dan `state` dengan nilai `comment: false`. Saya cek formulir HTML berhasil dimuat. Namun, ketika saya masuk melalui panel, lalu mengedit sebuah `page` yang terkait dengan isian `yaml` saya di atas. Saya meng-"update"-nya. Ternyata `yaml` yang saya buat di atas dihapus. Apakah ini karena formulir untuk membuat postingan di panel tidak memiliki `input`berupa `type` dan `state`?

Di masa mendatang, saya berharap opsi untuk menampilkan/tidak sebuah komentar dapat diakses via panel seperti ekstensi `pass`.
